context:
  version: "0.9.7"

package:
  name: jjui
  version: ${{ version }}

source:
  url: https://github.com/idursun/jjui/archive/refs/tags/v${{ version }}.tar.gz
  sha256: ba400c7c7fa6ea490ba271895cc8aabba409004b690040f8de69fe625e09b546

build:
  number: 0
  script:
    - go-licenses save ./cmd/jjui --save_path=license-files --ignore github.com/mattn/go-localereader
    - if: unix
      then: |
        go build -v -ldflags="-s -w" -o $PREFIX/bin/jjui ./cmd/jjui
        cp -r ${RECIPE_DIR}/license-files/* ${SRC_DIR}/license-files
      else: |
        go build -v -ldflags="-s" -o %LIBRARY_BIN%\jjui.exe .\cmd\jjui
        xcopy /s %RECIPE_DIR%\license-files\* %SRC_DIR%\license-files

requirements:
  build:
    - ${{ compiler('go-nocgo') }}
    - go-licenses

tests:
  - script:
      - jjui --version

about:
  homepage: https://idursun.github.io/jjui
  repository: https://github.com/idursun/jjui
  documentation: https://idursun.github.io/jjui
  summary: TUI for Jujutsu (JJ) VCS
  description: |
    Terminal user interface for working with Jujutsu version control system.
  license: MIT
  license_file:
    - LICENSE
    - license-files/

extra:
  recipe-maintainers:
    - VasanthakumarV
